name: CI
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Run!"
      - name: Build AUR Package (test)
        uses: DuckSoft/build-aur-action@v1.1
        with:
          repo-name: hello
      - name: LS
        run: |
          uname -a
          ls -al *
          ls -al pkg
          pacman
