name: CI
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Build AUR Package
        uses: DuckSoft/build-aur-action@v1.1
        with:
          repo-name: qv2ray-dev-git
