name: CI

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-18.04
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - name: Build Arch Linux package
      - uses: actions/checkout@v1
      - run: ls && uname -a
